#version: '3'
services:
 rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmq
   ports:
     - "5672:5672"   # RabbitMQ default port for AMQP
     - "15672:15672" # RabbitMQ Management UI

 amqp_consumer:
   build: ./backend/amqp
   container_name: amqp_consumer
   depends_on:
     - rabbitmq
   environment:
     - RABBITMQ_HOST=rabbitmq

 amqp_producer:
   build: ./backend/amqp
   command: ["python", "producer.py"]
   depends_on:
     - rabbitmq

 mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./backend/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf  # Point to the config file
    ports:
      - "1883:1883"  
      - "9001:9001"  

 sse-server:
    build:
      context: ./backend/sse
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

 websocket-server:
    build:
      context: ./backend/websocket
    ports:
      - "5002:5002"  # Expose port 5002 for WebSocket      
  
 streamlit:
    build: ./frontend/streamlit
    ports:
      - "8501:8501"
    depends_on:
      - rabbitmq
      - mosquitto
      - sse-server
      - websocket-server         